apiVersion: v1
kind: Service
metadata:
  name: listd-service

spec:
  type: ClusterIP
  selector:
    app: listd
  ports:
    - port: 3000 # Service (virtual network) abstraction port
      targetPort: 3000 # Container port